# Generated by Django 2.2.19 on 2023-01-31 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20230131_1243'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='rules',
            field=models.TextField(blank=True, null=True),
        ),
    ]
